language: node
node_js: "10.16"
sudo: true
services:
- docker
env:
  global:
  - secure: Kn/LPAkEB4LeAukWmnJQ66nJHdw8t0Nqk5VvntdsrvtRQldBrlwyw22MENk+Rhs+Qj0BwtAasEYvBZUO96kJt2RFe2E8z1dRKZ2mMDuAJlG0tBRxJVDGaojcjRZpPmK3tZJjwBkzTMZEl+QFW68pM2I/+Sb5VdB3Pp/Iot/+lIhNd/Kr9YIrh4fpznA6yQ4Gu8d1PP/rcAhW3AWR34MQYP872Gf0IhBpqgph40vsZoQxRKqi6RAhwfXXhZdwqraix6IMlzE3SbQ87EaSVLW4vHmYg3mkhDVVisPW30aBQMVQyudifVRnXqRU0cxQ8sKIIsLn0Wet58Vy1qBXe9gRZoY0enaPXGI9GObXtDxXBmdBfj6vCMTTGhCAbpM9LLC9Czky6qtyaATJx8m28saVKaOadqH2F146xxw43McSD+/HfysaZQTegjNiFt5lfmGpo4/VE8sS+Q+5eiJiz1G27u3GvyOYgWxSbCpkH8K3sDk5KGoWrsfH6FkAxZS3m76ZIqX3BY7WNH5C5p35S6rJieCro6W+MlhfkuU3MiJE3GExValK/fEP/0s0AoyvYQlHOqcp3/yn0LdoxOqpaxVwXV8969CAQjrWnAoVJuHISjsS5INhioKSoYKd/QQMMD6LFE/tM6h24OlGrC2CRsxnqM/5sRrtogjAaLITzPplITY=
  - secure: nzPWZX19n3MB5mNopfaQseV9VZajbCm/J154wgNUjgz65OrOor8tjIutyX4TxyO3f6FZgeRUHuImjSZ9M0PR6Z8p4cAxzgeHXa5VdGD4eHSJtdtPJUnZ5qUEDceP1JUxGHcH2hImHAP1Y08bJutjcop33mOmghanjrf8mmADnc6F9mT3BdtleKN+JnQmVqksPbCqdTcrjfN3fO4wjb2lLpTF0UAEAnTjj7osg5OK2TkHOMGgRcpoY67X+/5gnzNUOHDogJ/l+RgpHlz1uywVqRDsL2ERhO6XqR/KoOmOgywhQj8OjI5wVuhLMzBHCZOedbdtS9KIkvZxyj8Du9U2lgPZww59uzEIm0B8zEYGPTLzOI0ipJ2QCm+T226NwNQayFtwaKMvyLRNgFvh2EbM43a0i0QtzcpTDk2Foxfg89RCkS0Asb7plOCHrKUbEKRQWtJJqNmHTy/cx2aDyp1319lEXryYzR45KtclmBWevjo7kQqj1L/Xd0/jUGJNwIyFgxLaS+rIoETdTOTbtkO/usji3c96fVUfvy7iFTDN9oPa2u2RaYeB69SsE76Mb5x0/WXpjKVQV7P97YRdxgmwwtdJJ64kb3BToXgcr4kU8rP47Qiol1R5KVawLOsBdlfRsKDd5n0kcHqZykRgzWFUFQUXkRVCCV64tsUMP1x8gao=
  - secure: pwYBg13ASuphHMmd/ZghkcDU2jed5R5U84Ie8iPVouVzf00Xsjj/8ZoxC7MtuLxonQ623dyKsjDtnooiUdEzt5zuuVEwaIafsX5zqlgjI6+nCQ0YkFELhugTVXlFHRPyKeblVOH1WCviNnsXayXXdMjwaMffHGzwdUKiBwjMiOAP7aUD6ly1aKCq3AE07+sc8pyJVnZlu5cYQHmYjVwqvNnnjnXjMPgnx7zp+PsCdxY/m7riX/agrmupNfeM+NUgdZDyBgl1bCNc9yf4HQZfy/MAP6k9R8TYRmR1qgIMIdDKsdPzvn/NEbncixlHBf5Rdq/lWjybZXvt0W3lRmsNs2kROnzkQCb7PUPybp6Lgj2oIdqOMDlYvkgWVTbxHQ5mv5hiNaZ17Kf9pRX5XMqluUqfdNfwa7aQU5oOXLeyxmWu0xXcH5sxdAxmw3+iM0t++yng2/ALuU7Ttb3MaiIYGEyCtmqCzvc6FZZJDWGo6G6bu6t+7ndYCTfudJ+HXh4NKbFPNyC6FqU8MUel6xa1iQGReEdQ0JSrOqvC1D9TnvN4qQdpGxpHdLSSW4NJtIF+91+DUpAeKCF7uH62n3rrVbyRq2nA6ZFgmjJVverVMm5euG+o+6Q4IpBMoiL22ftcy0q+hcRshcAZORhfcQmxPgirC8K/+QB+JA29zCvDSpU=
install:
  - node --version
  - java -version
  - npm install
before_script: mvn package
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker images
- docker tag configurator $DOCKER_USERNAME/configurator
- docker push $DOCKER_USERNAME/configurator
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "${TRAVIS_BUILD_DIR}/target/configurator.war"
  skip_cleanup: true
  on:
    tags: true
